---
title: "processing_flux"
output: html_document
date: "2023-08-23"
---

```{r}
library(tidyverse)
library(lubridate)
library(seacarb)
library(AquaEnv)
```

```{r}
#Read in DIC and TA data
ids <- read_csv(here::here("Data/sample_list.csv"))

dic <- read_csv(here::here("Data/dic_2023.csv")) %>%
  left_join(ids) %>%
  mutate(id = paste(river, site, chamber_id, sep = "_"),
         site = paste(river, site, sep = "_"),
         date = mdy(date)) %>%
  select(-notes)

#read in TA
ta <- read_csv(here::here("Data/ta_2023.csv")) %>%
  select(-sample) %>%
  left_join(ids) %>%
  mutate(id = paste(river, site, chamber_id, sep = "_"),
         site = paste(river, site, sep = "_"),
         date = mdy(date)) %>%
           select(-notes)

#read in nutrients
nuts <- read_csv(here::here("Data/nutrients.csv")) %>%
  left_join(ids) %>%
  mutate(id = paste(river, site, chamber_id, sep = "_"),
         site = paste(river, site, sep = "_")) %>%
  select(-notes)

#read in logger data
load("Data/loggers_processed.RData")

plant_weight <- read_csv("Data/biomass.csv") %>%
  filter(ag_bg != "sediment") %>%
  mutate(id = paste(river, site, chamber_id, sep = "_"),
         site = paste(river, site, sep = "_")) %>%
  group_by(date, id, ag_bg) %>%
  summarize(plant_weight_g = sum(dry_mass_g)) %>%
  pivot_wider(values_from = plant_weight_g, names_from = ag_bg)

vols <- read_csv("Data/chamber_volume_calcs.csv") %>%
  mutate(id = paste(river, site, chamber_id, sep = "_"),
         vol_l = case_when(is.na(vol_l) ~ mean(vol_l[bag_size == "small"], na.rm = TRUE),
                           TRUE ~ vol_l)) %>%
  select(date, id, vol_l)

times_discrete <- read_csv("Data/sample_times.csv") %>%
  mutate(id = paste(river, site, chamber_id, sep = "_"),
         site = paste(river, site, sep = "_")) %>%
  select(-c(notes, month, day, river))
```


```{r}
#Calculate O2 flux rates.
o2_change <- function(do){
  delta_o <- rep(NA, length(do)) 
  for(i in 2:length(do)) {delta_o[i] = do[i] - do[i-1]}
  delta_o
}

rate_alt <- logger_join %>%
  group_by(date, id) %>%
  filter(abs(datetime - T1) == min(abs(datetime - T1)) | 
         abs(datetime - T2) == min(abs(datetime - T2))) %>%
  arrange(date, id, datetime) %>%
  ungroup() %>%
  mutate(time = rep(c("T1", "T2"), n()/2),
         timediff = as.numeric(T2 - T1)) %>%
  pivot_wider(values_from = do_mg_l, names_from = time, id_cols = c(date, id, timediff)) %>%
  mutate(rate_mg_l_h_alt = (T2 - T1)/timediff) %>%
  select(-c(T1, T2, timediff))


o2_flux <- logger_join %>%
  select(-c(T1, T2)) %>%
  group_by(date, id, site, treatment, chamber_id) %>%
  mutate(flux_mg_l = o2_change(do_mg_l),
        delta_t_h = 0.08333) %>%
  summarize(time_h = sum(delta_t_h),
            o2_rate_mg_l_h = sum(flux_mg_l, na.rm = TRUE)/time_h,
            depth_m = mean(depth_m, na.rm = TRUE)) %>%
  ungroup() %>%
  left_join(rate_alt) %>%
  mutate(ratediff = o2_rate_mg_l_h - rate_mg_l_h_alt,
         o2_rate_mg_l_h = case_when(abs(ratediff) > 0.5 ~ rate_mg_l_h_alt,
                                 TRUE ~ o2_rate_mg_l_h)) %>%
  select(-c(rate_mg_l_h_alt, ratediff)) %>%
  left_join(plant_weight) %>%
  left_join(vols) %>%
  mutate(o2_rate_mmol_l_h = o2_rate_mg_l_h / 32,
         o2_rate_mmol_m2_h = if_else(str_detect(treatment, "W|AMBIENT"),
                             o2_rate_mg_l_h * 1000 * depth_m  / 32,
                             o2_rate_mmol_l_h * vol_l / 0.018),
         o2_rate_mmol_g_sav_h = o2_rate_mmol_l_h * vol_l / ag) %>%
  select(-c(time_h)) %>%
  drop_na(site) %>%
  drop_na(chamber_id)
```


```{r}
#Plot fluxes (mg/l/h) to check
flux_list <- o2_flux %>%
  group_by(date) %>%
  group_split()

fluxplot1 <- function(x){
ggplot(x, aes(x = chamber_id, y = o2_rate_mmol_g_sav_h, fill = treatment)) +
  geom_bar(stat="identity") +
  facet_wrap(~site) +
  labs(x = "Chamber ID", y = expression("O"[2]~"flux (mmol m"^-2~"h"^-1*")"),
       title = paste("Oxygen fluxes", x$date[1]),
       subtitle = "(not normalized to biomass or chamber volume)") +
  theme_light()
}

map(flux_list, fluxplot1)
```

```{r}
#calculate change in pH
delta_ph <- logger_join %>%
  group_by(date, id) %>%
  filter(abs(datetime - T1) == min(abs(datetime - T1)) | 
         abs(datetime - T2) == min(abs(datetime - T2))) %>%
  arrange(date, id, datetime) %>%
  ungroup() %>%
  mutate(time = rep(c("T1", "T2"), n()/2),
         timediff = as.numeric(T2 - T1)) %>%
  pivot_wider(values_from = ph, names_from = time, id_cols = c(date, id, timediff)) %>%
  mutate(ph_change = T2 - T1) %>%
  select(-c(T1, T2, timediff))

ph_summary <- logger_join %>%
  group_by(date, id, site, treatment, chamber_id) %>%
  summarize(max_ph = max(ph, na.rm = TRUE),
            min_ph = min(ph, na.rm = TRUE), 
            mean_ph = mean(ph, na.rm = TRUE)) %>%
  left_join(delta_ph) %>%
  ungroup()
```


```{r}
#Plot delta pH
ph_list <- ph_summary %>%
  group_by(date) %>%
  group_split()

deltaphplot <- function(x){
  ggplot(x, aes(x = chamber_id, y = ph_change, fill = treatment)) +
  geom_bar(stat = "identity") +
  facet_wrap(~site) +
  labs(x = "Chamber ID", y = expression(Delta~"pH"),
       title = expression("pH change (pH"[T2]~"- pH"[T1]*")"),
       subtitle = x$date[1]) +
    ylim(c(-0.5, 2)) +
  theme_light()
}

map(ph_list, deltaphplot)
```


```{r}
#Calculate DIC change
depth_avg <- logger_join %>%
  select(-c(T1, T2)) %>%
  group_by(date, site) %>%
  summarize(depth_m = mean(depth_m, na.rm = TRUE))

dic_flux <- dic %>%
  left_join(depth_avg) %>%
  select(date, id, treatment, replicate, chamber_id, depth_m, dic_mmol, sample) %>%
  pivot_wider(names_from = sample, values_from = dic_mmol) %>%
  mutate(dic_change_mmol_l = T2 - T1,
         dic_t1 = T1) %>%
  select(-T1, -T2) %>%
  left_join(times_discrete) %>%
  left_join(vols) %>%
  left_join(plant_weight) %>%
  mutate(time_change = as.numeric(T2 - T1) / 3600,
         dic_rate_mmol_l_h = dic_change_mmol_l / time_change,
         dic_rate_mmol_m2_h = ifelse(treatment %in% c("W-D", "W-L"), dic_rate_mmol_l_h *1000 * depth_m,
                                     dic_rate_mmol_l_h * vol_l / 0.018),
         dic_rate_mmol_g_sav_h = dic_rate_mmol_l_h * vol_l / ag) %>%
  select(date, id, treatment, chamber_id, dic_t1, dic_rate_mmol_l_h, dic_rate_mmol_m2_h, dic_rate_mmol_g_sav_h)
```


```{r}
#Calculate TA change
ta_flux <- ta %>%
  select(date, id, treatment, replicate, chamber_id, ta_umol_l, sample) %>%
  pivot_wider(names_from = sample, values_from = ta_umol_l) %>%
  mutate(ta_change_umol_l = T2 - T1,
         ta_t1 = T1) %>%
  left_join(depth_avg) %>%
  select(-T1, -T2) %>%
  left_join(times_discrete) %>%
  left_join(vols) %>%
  left_join(plant_weight) %>%
  mutate(time_change = as.numeric(T2 - T1) / 3600,
         ta_rate_umol_l_h = ta_change_umol_l / as.numeric(time_change),
         ta_rate_mmol_m2_h = ifelse(treatment %in% c("W-D", "W-L"), ta_rate_umol_l_h * depth_m,
                                    ta_rate_umol_l_h * vol_l / 0.018 / 1000),
         ta_rate_mmol_g_sav_h = ta_rate_umol_l_h * vol_l / ag / 1000) %>%
  select(date, id, treatment, chamber_id, ta_t1, ta_rate_umol_l_h, ta_rate_mmol_m2_h, ta_rate_mmol_g_sav_h)
```


```{r}
#Calculate nutrient fluxes
po4 <- nuts %>%
  filter(parameter == "po4_p_mg_l") %>%
  select(date, id, treatment, replicate, chamber_id, value, sample) %>%
  pivot_wider(names_from = sample, values_from = value) %>%
  mutate(change_umol_l = (T2 - T1) * 1000/31,
         date = mdy(date)) %>%
  select(-T1, -T2) %>%
  left_join(times_discrete) %>%
  left_join(vols) %>%
  left_join(plant_weight) %>%
  mutate(time_change = as.numeric(T2 - T1) / 3600,
         po4_rate_umol_l_h = change_umol_l / as.numeric(time_change),
         po4_rate_umol_m2_h = po4_rate_umol_l_h * vol_l / 0.018,
         po4_rate_umol_g_sav_h = po4_rate_umol_l_h * vol_l / ag) %>%
  select(date, id, po4_rate_umol_l_h, po4_rate_umol_m2_h, po4_rate_umol_g_sav_h)

no23 <- nuts %>%
  filter(parameter == "no23_n_mg_l") %>%
  select(date, id, treatment, replicate, chamber_id, value, sample) %>%
  pivot_wider(names_from = sample, values_from = value) %>%
  mutate(change_umol_l = (T2 - T1) * 1000/14,
         date = mdy(date)) %>%
  select(-T1, -T2) %>%
  left_join(times_discrete) %>%
  left_join(vols) %>%
  left_join(plant_weight) %>%
  mutate(time_change = as.numeric(T2 - T1) / 3600,
         no23_rate_umol_l_h = change_umol_l / as.numeric(time_change),
         no23_rate_umol_m2_h = no23_rate_umol_l_h * vol_l / 0.018,
         no23_rate_umol_g_sav_h = no23_rate_umol_l_h * vol_l / ag) %>%
  select(date, id, no23_rate_umol_l_h, no23_rate_umol_m2_h, no23_rate_umol_g_sav_h)

nh3 <- nuts %>%
  filter(parameter == "nh3_n_mg_l") %>%
  select(date, id, treatment, replicate, chamber_id, value, sample) %>%
  pivot_wider(names_from = sample, values_from = value) %>%
  mutate(change_umol_l = (T2 - T1) * 1000/14,
         date = mdy(date)) %>%
  select(-T1, -T2) %>%
  left_join(times_discrete) %>%
  left_join(vols) %>%
  left_join(plant_weight) %>%
  mutate(time_change = as.numeric(T2 - T1) / 3600,
         nh3_rate_umol_l_h = change_umol_l / as.numeric(time_change),
         nh3_rate_umol_m2_h = nh3_rate_umol_l_h * vol_l / 0.018,
         nh3_rate_umol_g_sav_h = nh3_rate_umol_l_h * vol_l / ag) %>%
  select(date, id, nh3_rate_umol_l_h, nh3_rate_umol_m2_h, nh3_rate_umol_g_sav_h)
```

Calculate other co2sys params and fluxes
```{r}
temp_mean <- logger_join %>%
  group_by(date) %>%
  summarize(temp_mean_c = mean(temp_c, na.rm = TRUE))

co2 <- dic %>%
  left_join(ta) %>%
  select(-temp_c) %>%
  mutate(ta_mol_kg = ta_umol_kg / 1000000,
         dic_mol_kg = dic_mmol / 1007) %>%
  left_join(temp_mean) %>%
  select(date, id, treatment, sample, chamber_id, site, ta_mol_kg, dic_mol_kg, temp_mean_c, salinity) %>%
  drop_na(ta_mol_kg)

#carb(flag = 15, var1 = co2$ta_mol_kg, var2 = co2$dic_mol_kg, S = co2$salinity, T = co2$temp_mean_c, P = 0, k1k2 = "r")

calcs <- aquaenv(S = co2$salinity, t = co2$temp_mean_c, P = 1, d = 1, TA = co2$ta_mol_kg, SumCO2 = co2$dic_mol_kg)

co2sys <- co2 %>% 
  bind_cols(calcs$pH, calcs$HCO3, calcs$CO3, calcs$omega_calcite, calcs$omega_aragonite, calcs$CO2, calcs$density, calcs$CO3) %>%
  rename(ph_calc = `...11`, hco3_calc = `...12`, co3_calc = `...13`, omega_calcite = `...14`, omega_aragonite = `...15`, co2 = `...16`, density = `...17`, co3 = `...18`)
```

```{r}
hco3 <- co2sys %>%
  select(date, id, treatment, density, chamber_id, sample, hco3_calc) %>%
  pivot_wider(names_from = sample, values_from = hco3_calc) %>%
  mutate(change_mmol_l = (T2 - T1) * density) %>%
  select(-T1, -T2) %>%
  left_join(times_discrete) %>%
  left_join(vols) %>%
  left_join(plant_weight) %>%
  mutate(time_change = as.numeric(T2 - T1) / 3600,
         hc03_rate_mmol_l_h = change_mmol_l / as.numeric(time_change),
         hc03_rate_mmol_m2_h = hc03_rate_mmol_l_h * vol_l / 0.018,
         hc03_rate_mmol_g_sav_h = hc03_rate_mmol_l_h * vol_l / ag) %>%
  select(date, id, hc03_rate_mmol_l_h, hc03_rate_mmol_m2_h, hc03_rate_mmol_g_sav_h)
```

```{r}
co2_calc <- co2sys %>%
  select(date, id, treatment, chamber_id, density, sample, co2) %>%
  pivot_wider(names_from = sample, values_from = co2) %>%
  mutate(change_mmol_l = (T2 - T1) * density) %>%
  select(-T1, -T2) %>%
  left_join(times_discrete) %>%
  left_join(vols) %>%
  left_join(plant_weight) %>%
  mutate(time_change = as.numeric(T2 - T1) / 3600,
         co2_rate_mmol_l_h = change_mmol_l / as.numeric(time_change),
         co2_rate_mmol_m2_h = co2_rate_mmol_l_h * vol_l / 0.018,
         co2_rate_mmol_g_sav_h = co2_rate_mmol_l_h * vol_l / ag) %>%
  select(date, id, co2_rate_mmol_l_h, co2_rate_mmol_m2_h, co2_rate_mmol_g_sav_h)
```

```{r}
co3 <- co2sys %>%
  select(date, id, treatment, chamber_id, density, sample, co3) %>%
  pivot_wider(names_from = sample, values_from = co3) %>%
  mutate(change_mmol_l = (T2 - T1) * density) %>%
  select(-T1, -T2) %>%
  left_join(times_discrete) %>%
  left_join(vols) %>%
  left_join(plant_weight) %>%
  mutate(time_change = as.numeric(T2 - T1) / 3600,
         co3_rate_mmol_l_h = change_mmol_l / as.numeric(time_change),
         co3_rate_mmol_m2_h = co3_rate_mmol_l_h * vol_l / 0.018,
         co3_rate_mmol_g_sav_h = co3_rate_mmol_l_h * vol_l / ag) %>%
  select(date, id, co3_rate_mmol_l_h, co3_rate_mmol_m2_h, co3_rate_mmol_g_sav_h)
```

```{r}
ph_calc <- co2sys %>%
  select(date, id, treatment, chamber_id, density, sample, ph_calc) %>%
  pivot_wider(names_from = sample, values_from = ph_calc) %>%
  mutate(change = (T2 - T1)) %>%
  select(-T1, -T2) %>%
  left_join(times_discrete) %>%
  left_join(vols) %>%
  left_join(plant_weight) %>%
  mutate(time_change = as.numeric(T2 - T1) / 3600,
         ph_change_calc = change / as.numeric(time_change)) %>%
  select(date, id, ph_change_calc)
```

Join flux data
```{r}
flux_data <-  dic_flux %>%
  full_join(ta_flux) %>%
  mutate(site = substr(id, 1, 6)) %>%
  full_join(po4) %>%
  full_join(no23) %>%
  full_join(nh3) %>%
  full_join(hco3) %>%
  full_join(co3) %>%
  full_join(co2_calc) %>%
 full_join(o2_flux) %>%
  full_join(ph_summary) %>%
  mutate(month = month(date),
    season = case_when(month %in% 5:6 ~ "spring",
                            month == 8 ~ "summer",
                            month == 10 ~ "fall"))
```

Save data
```{r}
save(flux_data, file = "Data/flux_data.RData")
```

DIC-TA plot YOR_BR
```{r}
tawide <- dic %>%
  left_join(ta) %>%
  mutate(dic_umol_kg = dic_mmol *1000*1000/water_kg_m3) %>%
  filter(site == "YOR_BR", 
         season == "spring") %>%
  mutate(ta_umol_kg = case_when(site == "POT_BR" & ta_umol_kg > 1675 ~ NA,
                   site == "POT_BR" & ta_umol_kg < 1500 ~ NA,
                   TRUE ~ ta_umol_kg)) %>%
  select(treatment, replicate, sample, chamber_id, ta_umol_kg) %>%
  group_by(treatment, sample) %>%
  summarize(ta = mean(ta_umol_kg, na.rm = TRUE)) %>%
  pivot_wider(names_from = sample, values_from = ta) %>%
  rename(tat1 = T1, tat2 = T2)

dicwide <- dic %>%
  left_join(ta) %>%
  mutate(dic_umol_kg = dic_mmol *1000*1000/water_kg_m3) %>%
  filter(site == "YOR_BR", 
         season == "spring") %>%
  mutate(ta_umol_kg = case_when(site == "POT_BR" & ta_umol_kg > 1675 ~ NA,
                   site == "POT_BR" & ta_umol_kg < 1500 ~ NA,
                   TRUE ~ ta_umol_kg)) %>%
  select(treatment, replicate, sample, chamber_id, dic_umol_kg) %>%
  group_by(treatment, sample) %>%
  summarize(dic = mean(dic_umol_kg, na.rm = TRUE)) %>%
  pivot_wider(names_from = sample, values_from = dic) %>%
  rename(dict1 = T1, dict2 = T2)
  
segdat <- left_join(tawide, dicwide) %>%
  mutate(dist = sqrt((dict2-dict1)^2 + (tat2-tat1)^2),
        x_aerresp = dict1 + dist / sqrt(1+-0.2^2),
        y_aerresp = tat1 - (-0.2 * dist) / sqrt(1+-0.2^2),
        x_sulfred = dict1 - dist / sqrt(1+1^2),
        y_sulfred = tat1 - (1 * dist) / sqrt(1+1^2),
        x_calc = dict1 - dist / sqrt(1+2^2),
        y_calc = tat1 - (2 * dist) / sqrt(1+2^2),
        x_nh4 = dict1 - dist / sqrt(1+0.15^2),
        y_nh4 = tat1 - (0.15 * dist) / sqrt(1+0.15^2),
        x_no3 = dict1 - dist / sqrt(1-0.15^2),
        y_no3 = tat1 - (-0.15 * dist) / sqrt(1+-0.15^2),
        x_dnf = dict1 - dist / sqrt(1+0.8^2),
        y_dnf = tat1 - (0.8 * dist) / sqrt(1+0.8^2))

dic %>%
  left_join(ta) %>%
  mutate(dic_umol_kg = dic_mmol *1000*1000/water_kg_m3) %>%
  filter(site == "YOR_BR") %>%
  group_by(treatment, sample) %>%
  summarize(dic = mean(dic_umol_kg, na.rm = TRUE),
            ta = mean(ta_umol_kg, na.rm = TRUE)) %>%
ggplot(aes(x = dic, y = ta, color = treatment)) +
  geom_point() +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = dict2, yend = tat2),
               arrow = arrow(length = unit(0.1, "inches"))) +
  facet_wrap(~treatment, scales = "free") +
  labs(x = expression("DIC ("*mu*"mol kg"^-1*")"), y = expression("TA ("*mu*"mol kg"^-1*")")) +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_aerresp, yend = y_aerresp), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_aerresp, y = y_aerresp, label = "aer_resp"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_sulfred, yend = y_sulfred), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_sulfred, y = y_sulfred, label = "sulf_red"), color = "#9c9c9c")+
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_calc, yend = y_calc), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_calc, y = y_calc, label = "calc"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_nh4, yend = y_nh4), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_nh4, y = y_nh4, label = "nh4_assim"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_dnf, yend = y_dnf), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_dnf, y = y_dnf, label = "dnf"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_no3, yend = y_no3), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_no3, y = y_no3, label = "no3_assim"), color = "#9c9c9c") +
  theme_light()
```

DIC-TA plot POT_BR
```{r}
tawide <- dic %>%
  left_join(ta) %>%
  mutate(dic_umol_kg = dic_mmol *1000*1000/water_kg_m3) %>%
  filter(site == "POT_BR", 
         season == "spring") %>%
  mutate(ta_umol_kg = case_when(site == "POT_BR" & ta_umol_kg > 1675 ~ NA,
                   site == "POT_BR" & ta_umol_kg < 1500 ~ NA,
                   TRUE ~ ta_umol_kg)) %>%
  select(treatment, replicate, sample, chamber_id, ta_umol_kg) %>%
  group_by(treatment, sample) %>%
  summarize(ta = mean(ta_umol_kg, na.rm = TRUE)) %>%
  pivot_wider(names_from = sample, values_from = ta) %>%
  rename(tat1 = T1, tat2 = T2)

dicwide <- dic %>%
  left_join(ta) %>%
  mutate(dic_umol_kg = dic_mmol *1000*1000/water_kg_m3) %>%
  filter(site == "POT_BR", 
         season == "spring") %>%
  mutate(ta_umol_kg = case_when(site == "POT_BR" & ta_umol_kg > 1675 ~ NA,
                   site == "POT_BR" & ta_umol_kg < 1500 ~ NA,
                   TRUE ~ ta_umol_kg)) %>%
  select(treatment, replicate, sample, chamber_id, dic_umol_kg) %>%
  group_by(treatment, sample) %>%
  summarize(dic = mean(dic_umol_kg, na.rm = TRUE)) %>%
  pivot_wider(names_from = sample, values_from = dic) %>%
  rename(dict1 = T1, dict2 = T2)
  
segdat <- left_join(tawide, dicwide) %>%
  mutate(dist = sqrt((dict2-dict1)^2 + (tat2-tat1)^2),
        x_aerresp = dict1 + dist / sqrt(1+-0.2^2),
        y_aerresp = tat1 - (-0.2 * dist) / sqrt(1+-0.2^2),
        x_sulfred = dict1 - dist / sqrt(1+1^2),
        y_sulfred = tat1 - (1 * dist) / sqrt(1+1^2),
        x_calc = dict1 - dist / sqrt(1+2^2),
        y_calc = tat1 - (2 * dist) / sqrt(1+2^2),
        x_nh4 = dict1 - dist / sqrt(1+0.15^2),
        y_nh4 = tat1 - (0.15 * dist) / sqrt(1+0.15^2),
        x_no3 = dict1 - dist / sqrt(1-0.15^2),
        y_no3 = tat1 - (-0.15 * dist) / sqrt(1+-0.15^2),
        x_dnf = dict1 - dist / sqrt(1+0.8^2),
        y_dnf = tat1 - (0.8 * dist) / sqrt(1+0.8^2))

dic %>%
  left_join(ta) %>%
  mutate(dic_umol_kg = dic_mmol *1000*1000/water_kg_m3,
         ta_umol_kg = case_when(site == "POT_BR" & ta_umol_kg > 1675 ~ NA,
                   site == "POT_BR" & ta_umol_kg < 1500 ~ NA,
                   TRUE ~ ta_umol_kg)) %>%
  filter(site == "POT_BR") %>%
  group_by(treatment, sample) %>%
  summarize(dic = mean(dic_umol_kg, na.rm = TRUE),
            ta = mean(ta_umol_kg, na.rm = TRUE)) %>%
ggplot(aes(x = dic, y = ta, color = treatment)) +
  geom_point() +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = dict2, yend = tat2),
               arrow = arrow(length = unit(0.1, "inches"))) +
  facet_wrap(~treatment, scales = "free") +
  labs(x = expression("DIC ("*mu*"mol kg"^-1*")"), y = expression("TA ("*mu*"mol kg"^-1*")")) +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_aerresp, yend = y_aerresp), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_aerresp, y = y_aerresp, label = "aer_resp"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_sulfred, yend = y_sulfred), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_sulfred, y = y_sulfred, label = "sulf_red"), color = "#9c9c9c")+
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_calc, yend = y_calc), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_calc, y = y_calc, label = "calc"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_nh4, yend = y_nh4), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_nh4, y = y_nh4, label = "nh4_assim"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_dnf, yend = y_dnf), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_dnf, y = y_dnf, label = "dnf"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_no3, yend = y_no3), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_no3, y = y_no3, label = "no3_assim"), color = "#9c9c9c") +
  theme_light()
```

DIC-TA plot YOR_FW
```{r}
tawide <- dic %>%
  left_join(ta) %>%
  mutate(dic_umol_kg = dic_mmol *1000*1000/water_kg_m3) %>%
  filter(site == "YOR_FW", 
         season == "spring") %>%
  select(treatment, replicate, sample, chamber_id, ta_umol_kg) %>%
  group_by(treatment, sample) %>%
  summarize(ta = mean(ta_umol_kg, na.rm = TRUE)) %>%
  pivot_wider(names_from = sample, values_from = ta) %>%
  rename(tat1 = T1, tat2 = T2)

dicwide <- dic %>%
  left_join(ta) %>%
  mutate(dic_umol_kg = dic_mmol *1000*1000/water_kg_m3) %>%
  filter(site == "YOR_FW", 
         season == "spring") %>%
  select(treatment, replicate, sample, chamber_id, dic_umol_kg) %>%
  group_by(treatment, sample) %>%
  summarize(dic = mean(dic_umol_kg, na.rm = TRUE)) %>%
  pivot_wider(names_from = sample, values_from = dic) %>%
  rename(dict1 = T1, dict2 = T2)
  
segdat <- left_join(tawide, dicwide) %>%
  mutate(dist = sqrt((dict2-dict1)^2 + (tat2-tat1)^2),
        x_aerresp = dict1 + dist / sqrt(1+-0.2^2),
        y_aerresp = tat1 - (-0.2 * dist) / sqrt(1+-0.2^2),
        x_sulfred = dict1 - dist / sqrt(1+1^2),
        y_sulfred = tat1 - (1 * dist) / sqrt(1+1^2),
        x_calc = dict1 - dist / sqrt(1+2^2),
        y_calc = tat1 - (2 * dist) / sqrt(1+2^2),
        x_nh4 = dict1 - dist / sqrt(1+0.15^2),
        y_nh4 = tat1 - (0.15 * dist) / sqrt(1+0.15^2),
        x_no3 = dict1 - dist / sqrt(1-0.15^2),
        y_no3 = tat1 - (-0.15 * dist) / sqrt(1+-0.15^2),
        x_dnf = dict1 - dist / sqrt(1+0.8^2),
        y_dnf = tat1 - (0.8 * dist) / sqrt(1+0.8^2))

dic %>%
  left_join(ta) %>%
  mutate(dic_umol_kg = dic_mmol *1000*1000/water_kg_m3) %>%
  filter(site == "YOR_FW") %>%
  group_by(treatment, sample) %>%
  summarize(dic = mean(dic_umol_kg, na.rm = TRUE),
            ta = mean(ta_umol_kg, na.rm = TRUE)) %>%
ggplot(aes(x = dic, y = ta, color = treatment)) +
  geom_point() +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = dict2, yend = tat2),
               arrow = arrow(length = unit(0.1, "inches"))) +
  facet_wrap(~treatment, scales = "free") +
  labs(x = expression("DIC ("*mu*"mol kg"^-1*")"), y = expression("TA ("*mu*"mol kg"^-1*")")) +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_aerresp, yend = y_aerresp), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_aerresp, y = y_aerresp, label = "aer_resp"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_sulfred, yend = y_sulfred), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_sulfred, y = y_sulfred, label = "sulf_red"), color = "#9c9c9c")+
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_calc, yend = y_calc), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_calc, y = y_calc, label = "calc"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_nh4, yend = y_nh4), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_nh4, y = y_nh4, label = "nh4_assim"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_dnf, yend = y_dnf), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_dnf, y = y_dnf, label = "dnf"), color = "#9c9c9c") +
  geom_segment(data = segdat, aes(x = dict1, y = tat1, xend = x_no3, yend = y_no3), color = "#9c9c9c") +
  geom_text_repel(data = segdat, aes(x = x_no3, y = y_no3, label = "no3_assim"), color = "#9c9c9c") +
  theme_light()
```
